"""
Module DB — nói chuyện với PostgreSQL thật theo đúng schema.sql.

LỊCH SỬ: trước đây là 1 file db.py duy nhất (2619 dòng / 89 hàm, "God
module" trộn company/job/auth/contact/application/audit_log/stats).
Đã tách theo domain (xem từng file con) để dễ tìm, dễ sửa, giảm
conflict khi nhiều người cùng sửa. File này CHỈ re-export lại toàn bộ
tên cũ (kể cả biến/hằng module-level như _pool, ACTION_LOG_RULES,
alias get_or_create_province) để KHÔNG phải sửa bất kỳ chỗ nào đang
`import db` / `import db as db_module` rồi gọi `db.xxx` ở nơi khác
trong repo — API bên ngoài giữ nguyên 100%, chỉ tổ chức lại bên trong.
"""

from db.connection import (
    is_valid_uuid,
    get_connection,
    init_pool,
    get_pooled_connection,
    release_connection,
    close_pool,
    apply_schema,
)
from db.lookups import (
    get_province_id,
    get_or_create_province,
    get_level_id,
)
from db.companies import (
    find_company_probe,
    get_or_create_company_by_profile,
    get_or_create_company,
    update_company_profile,
    patch_company_profile,
    company_exists_by_id,
    merge_companies,
    find_company_by_tax_id,
    update_company_profile_with_merge,
    get_companies_needing_profile_from_website,
    get_companies_needing_social_links,
    update_company_social_links,
    get_companies_needing_web_lookup,
    get_companies_needing_profile_backfill,
    list_companies,
    get_company_by_id,
    soft_delete_company,
)
from db.jobs import (
    get_open_jobs_with_source_url,
    probe_needs_enrichment,
    job_exists_by_source_url,
    get_job_probe_by_source_url,
    job_needs_detail_enrichment,
    update_job_fields,
    insert_job,
    count_jobs,
    find_manual_job_duplicate,
    create_manual_job,
    update_job,
    job_exists_by_id,
    list_jobs,
    get_job_by_id,
    get_jobs_by_company_id,
)
from db.stats import (
    get_stats_summary,
    get_job_engagement_counts,
    get_monthly_engagement_stats,
)
from db.auth import (
    get_user_by_email,
    get_user_by_id,
    create_user,
    update_user_password,
    record_failed_login,
    is_account_locked,
    reset_failed_login,
    create_refresh_token,
    get_refresh_token_by_hash,
    revoke_refresh_token,
    set_active_session_id,
    revoke_all_refresh_tokens_for_user,
    list_users,
    update_user_role,
    update_user_active_status,
    create_user_pending_verification,
    get_user_by_verify_token_hash,
    mark_email_verified,
    set_new_verify_token,
    set_password_reset_token,
    get_user_by_reset_token_hash,
    reset_password_with_token,
)
from db.contacts import (
    list_company_contacts,
    list_all_contacts,
    get_company_contact_by_id,
    create_company_contact,
    update_company_contact,
    assign_company_contact,
    soft_delete_company_contact,
    ContactHasLinksError,
    hard_delete_company_contact,
)
from db.applications import (
    create_job_application,
    list_applications_for_user,
    list_applications_for_job,
    delete_job_application,
    create_saved_job,
    list_saved_jobs_for_user,
    delete_saved_job,
    list_saved_jobs_for_job,
)
from db.audit_logs import (
    ACTION_LOG_RULES,
    NoteRequiredError,
    diff_changed_fields,
    log_action,
    list_audit_logs,
    get_audit_log_by_id,
    update_audit_log_note,
)
from db.crawl_runs import (
    ActiveCrawlExistsError,
    create_run as create_crawl_run,
    mark_running as mark_crawl_run_running,
    mark_done as mark_crawl_run_done,
    mark_error as mark_crawl_run_error,
    get_run as get_crawl_run,
    list_runs as list_crawl_runs,
    has_active_run as crawl_source_has_active_run,
    reconcile_orphaned_runs as reconcile_orphaned_crawl_runs,
    reconcile_stale_runs as reconcile_stale_crawl_runs,
    update_progress as update_crawl_run_progress,
    append_log as append_crawl_run_log,
    get_logs as get_crawl_run_logs,
    get_latest_run as get_latest_crawl_run,
)

__all__ = [
    "is_valid_uuid",
    "get_connection",
    "init_pool",
    "get_pooled_connection",
    "release_connection",
    "close_pool",
    "apply_schema",
    "get_province_id",
    "get_or_create_province",
    "get_level_id",
    "find_company_probe",
    "get_or_create_company_by_profile",
    "get_or_create_company",
    "update_company_profile",
    "patch_company_profile",
    "company_exists_by_id",
    "merge_companies",
    "find_company_by_tax_id",
    "update_company_profile_with_merge",
    "get_companies_needing_profile_from_website",
    "get_companies_needing_social_links",
    "update_company_social_links",
    "get_companies_needing_web_lookup",
    "get_companies_needing_profile_backfill",
    "list_companies",
    "get_company_by_id",
    "soft_delete_company",
    "get_open_jobs_with_source_url",
    "probe_needs_enrichment",
    "job_exists_by_source_url",
    "get_job_probe_by_source_url",
    "job_needs_detail_enrichment",
    "update_job_fields",
    "insert_job",
    "count_jobs",
    "find_manual_job_duplicate",
    "create_manual_job",
    "update_job",
    "job_exists_by_id",
    "list_jobs",
    "get_job_by_id",
    "get_jobs_by_company_id",
    "get_stats_summary",
    "get_job_engagement_counts",
    "get_monthly_engagement_stats",
    "get_user_by_email",
    "get_user_by_id",
    "create_user",
    "update_user_password",
    "record_failed_login",
    "is_account_locked",
    "reset_failed_login",
    "create_refresh_token",
    "get_refresh_token_by_hash",
    "revoke_refresh_token",
    "set_active_session_id",
    "revoke_all_refresh_tokens_for_user",
    "list_users",
    "update_user_role",
    "update_user_active_status",
    "create_user_pending_verification",
    "get_user_by_verify_token_hash",
    "mark_email_verified",
    "set_new_verify_token",
    "set_password_reset_token",
    "get_user_by_reset_token_hash",
    "reset_password_with_token",
    "list_company_contacts",
    "list_all_contacts",
    "get_company_contact_by_id",
    "create_company_contact",
    "update_company_contact",
    "assign_company_contact",
    "soft_delete_company_contact",
    "ContactHasLinksError",
    "hard_delete_company_contact",
    "create_job_application",
    "list_applications_for_user",
    "list_applications_for_job",
    "delete_job_application",
    "create_saved_job",
    "list_saved_jobs_for_user",
    "delete_saved_job",
    "list_saved_jobs_for_job",
    "ACTION_LOG_RULES",
    "NoteRequiredError",
    "diff_changed_fields",
    "log_action",
    "list_audit_logs",
    "get_audit_log_by_id",
    "update_audit_log_note",
    "ActiveCrawlExistsError",
    "create_crawl_run",
    "mark_crawl_run_running",
    "mark_crawl_run_done",
    "mark_crawl_run_error",
    "get_crawl_run",
    "list_crawl_runs",
    "crawl_source_has_active_run",
    "reconcile_orphaned_crawl_runs",
    "reconcile_stale_crawl_runs",
    "update_crawl_run_progress",
    "append_crawl_run_log",
    "get_crawl_run_logs",
    "get_latest_crawl_run",
]

