"""
Module DB — nói chuyện với PostgreSQL thật theo đúng schema.sql.

LỊCH SỬ: trước đây là 1 file db.py duy nhất (2619 dòng / 89 hàm, "God
module" trộn company/job/auth/contact/application/audit_log/stats).
Đã tách theo domain (xem từng file con) để dễ tìm, dễ sửa, giảm
conflict khi nhiều người cùng sửa. File này CHỈ re-export lại toàn bộ
tên cũ (kể cả biến/hằng module-level như _pool, ACTION_LOG_RULES,
alias get_or_create_province) để KHÔNG phải sửa bất kỳ chỗ nào đang
`import db` / `import db as db_module` rồi gọi `db.xxx` ở nơi khác
trong repo — API bên ngoài giữ nguyên 100%, chỉ tổ chức lại bên trong.
"""

from db.connection import (
    is_valid_uuid,
    get_connection,
    init_pool,
    get_pooled_connection,
    release_connection,
    close_pool,
    apply_schema,
    apply_migrations,
    baseline_migrations,
    list_pending_migrations,
)
from db.lookups import (
    get_province_id,
    get_or_create_province,
    get_level_id,
)
from db.companies import (
    find_company_probe,
    get_or_create_company_by_profile,
    get_or_create_company,
    update_company_profile,
    patch_company_profile,
    company_exists_by_id,
    merge_companies,
    find_company_by_tax_id,
    update_company_profile_with_merge,
    soft_delete_company,
)
from db.company_enrichment import (
    get_companies_needing_profile_from_website,
    get_companies_needing_social_links,
    update_company_social_links,
    get_companies_needing_web_lookup,
    get_companies_needing_profile_backfill,
)
from db.company_queries import (
    list_companies,
    get_company_by_id,
)
from db.company_analytics import (
    get_partnership_signals,
    get_company_data_health,
)
from db.jobs import (
    _UNSET as JOB_UNSET,
    JOB_CLOSED_REASONS,
    JOB_CLEARABLE_FIELD_TO_COLUMN,
    get_open_jobs_with_source_url,
    probe_needs_enrichment,
    job_exists_by_source_url,
    get_job_probe_by_source_url,
    job_needs_detail_enrichment,
    mark_source_detail_checked,
    update_job_fields,
    insert_job,
    count_jobs,
    find_manual_job_duplicate,
    find_similar_open_jobs,
    lock_job_dedup_key,
    JobDedupLockTimeout,
    JOB_DEDUP_LOCK_TIMEOUT_MS,
    create_manual_job,
    update_job,
    job_exists_by_id,
)
from db.job_recrawl import (
    link_repost_source,
    extend_job_deadline,
    find_repost_candidate,
    reopen_job_for_repost,
    AUTO_REOPEN_REASONS,
    find_jobs_by_source_url_regex,
    update_job_from_recrawl,
)
from db.job_level_recompute import (
    skip_updated_at_supported,
    list_level_recompute_candidates,
    compute_content_hashes_for_levels,
    get_jobs_by_content_hashes,
    count_duplicate_job_groups,
    write_recomputed_levels,
)
from db.job_duplicates import (
    list_duplicate_job_rows,
)
from db.job_merge import (
    list_merge_job_details,
    merge_job_group,
    merge_job_enum_supported,
    list_active_runs,
    MergeStaleError,
    MergeIntegrityError,
)
from db.job_queries import (
    list_jobs,
    get_job_by_id,
    get_jobs_by_company_id,
)
from db.job_health import (
    get_job_data_health,
)
from db.stats import (
    get_stats_summary,
    get_job_engagement_counts,
    get_monthly_engagement_stats,
)
from db.dashboard import (
    get_jobs_needing_push,
    get_stale_jobs,
    get_top_skills,
    get_salary_ranges,
    get_high_potential_companies_without_contact,
    get_contacts_needing_followup,
    get_company_job_activity,
    get_monthly_recap_counts,
)
from db.auth import (
    get_user_by_email,
    get_user_by_id,
    create_user,
    update_user_password,
    update_user_profile,
    record_failed_login,
    is_account_locked,
    reset_failed_login,
    create_refresh_token,
    get_refresh_token_by_hash,
    get_refresh_token_by_id,
    revoke_refresh_token,
    set_active_session_id,
    revoke_all_refresh_tokens_for_user,
    list_users,
    get_user_summary_by_id,
    update_user_role,
    update_user_active_status,
    create_user_pending_verification,
    get_user_by_verify_token_hash,
    mark_email_verified,
    set_new_verify_token,
    set_password_reset_token,
    get_user_by_reset_token_hash,
    reset_password_with_token,
)
from db.contacts import (
    list_company_contacts,
    list_all_contacts,
    get_company_contact_by_id,
    create_company_contact,
    update_company_contact,
    assign_company_contact,
    soft_delete_company_contact,
    ContactHasLinksError,
    hard_delete_company_contact,
)
from db.email_templates import (
    list_email_templates,
    get_email_template_by_id,
    create_email_template,
    patch_email_template,
    delete_email_template,
)
from db.applications import (
    create_job_application,
    list_applications_for_user,
    list_applications_for_job,
    delete_job_application,
    create_saved_job,
    list_saved_jobs_for_user,
    delete_saved_job,
    list_saved_jobs_for_job,
    list_closed_job_applications_with_cv,
    clear_application_cv,
    get_application_cv_url,
    set_application_cv_url,
    get_application_with_job_info,
)
from db.audit_logs import (
    ACTION_LOG_RULES,
    NoteRequiredError,
    diff_changed_fields,
    log_action,
    list_audit_logs,
    get_audit_log_by_id,
    update_audit_log_note,
)
from db.crawl_runs import (
    ActiveCrawlExistsError,
    create_run as create_crawl_run,
    mark_running as mark_crawl_run_running,
    mark_done as mark_crawl_run_done,
    mark_error as mark_crawl_run_error,
    get_run as get_crawl_run,
    list_runs as list_crawl_runs,
    has_active_run as crawl_source_has_active_run,
    reconcile_orphaned_runs as reconcile_orphaned_crawl_runs,
    reconcile_stale_runs as reconcile_stale_crawl_runs,
    update_progress as update_crawl_run_progress,
    append_log as append_crawl_run_log,
    get_logs as get_crawl_run_logs,
    get_latest_run as get_latest_crawl_run,
    get_recent_blocked_run as get_recent_blocked_crawl_run,
)
from db.crawl_snapshots import (
    save_snapshots as save_crawl_snapshots,
    list_snapshots as list_crawl_snapshots,
    get_snapshot as get_crawl_snapshot,
)
from db.crawl_batches import (
    create_batch as create_crawl_batch,
    advance_batch as advance_crawl_batch,
    mark_done as mark_crawl_batch_done,
    mark_error as mark_crawl_batch_error,
    get_batch as get_crawl_batch,
    get_batch_with_items as get_crawl_batch_with_items,
    list_batches as list_crawl_batches,
)
# 08/2026 (xem sql/migration_add_maintenance_runs.sql) — "Bảo trì dữ
# liệu" từ web dưới quyền admin, đối xứng db.crawl_runs ở trên nhưng
# generic hoá theo job_type thay vì source, cho 5 script:
# backfill_company_profiles.py, enrich_company_profile_from_website.py,
# enrich_company_web_info.py, get_company_fb_linkedin_link.py,
# check_expired_source_jobs.py — xem api/maintenance_runner.py.
from db.maintenance_runs import (
    ActiveMaintenanceRunExistsError,
    create_run as create_maintenance_run,
    mark_running as mark_maintenance_run_running,
    mark_done as mark_maintenance_run_done,
    mark_error as mark_maintenance_run_error,
    get_run as get_maintenance_run,
    list_runs as list_maintenance_runs,
    has_active_run as maintenance_job_type_has_active_run,
    reconcile_orphaned_runs as reconcile_orphaned_maintenance_runs,
    reconcile_stale_runs as reconcile_stale_maintenance_runs,
    append_log as append_maintenance_run_log,
    get_logs as get_maintenance_run_logs,
    get_logs_batch as get_maintenance_run_logs_batch,
    get_latest_run_per_job_type as get_latest_maintenance_run_per_job_type,
)
from db.messages import (
    MAX_PENDING_PER_STUDENT,
    DECLINE_COOLDOWN_DAYS,
    MAX_MESSAGE_ID,
    get_relationship,
    get_relationship_by_id,
    count_pending_for_student,
    create_pending_request,
    cancel_pending_request,
    reset_declined_to_pending,
    accept_relationship,
    decline_relationship,
    block_relationship,
    block_student_by_ss,
    unblock_relationship,
    ensure_accepted_by_ss,
    insert_message,
    get_message_by_id,
    get_messages_between,
    get_messages_since,
    mark_read,
    get_unread_count,
    get_conversation_with,
    list_conversations,
    list_pending_requests_for_ss,
    search_people,
)

__all__ = [
    "is_valid_uuid",
    "get_connection",
    "init_pool",
    "get_pooled_connection",
    "release_connection",
    "close_pool",
    "apply_schema",
    "apply_migrations",
    "baseline_migrations",
    "list_pending_migrations",
    "get_province_id",
    "list_email_templates",
    "get_email_template_by_id",
    "create_email_template",
    "patch_email_template",
    "delete_email_template",
    "get_or_create_province",
    "get_level_id",
    "find_company_probe",
    "get_or_create_company_by_profile",
    "get_or_create_company",
    "update_company_profile",
    "patch_company_profile",
    "company_exists_by_id",
    "merge_companies",
    "find_company_by_tax_id",
    "update_company_profile_with_merge",
    "get_companies_needing_profile_from_website",
    "get_companies_needing_social_links",
    "update_company_social_links",
    "get_companies_needing_web_lookup",
    "get_companies_needing_profile_backfill",
    "list_companies",
    "get_company_by_id",
    "soft_delete_company",
    "get_partnership_signals",
    "get_company_data_health",
    "get_open_jobs_with_source_url",
    "probe_needs_enrichment",
    "job_exists_by_source_url",
    "get_job_probe_by_source_url",
    "job_needs_detail_enrichment",
    "mark_source_detail_checked",
    "update_job_fields",
    "insert_job",
    "link_repost_source",
    "extend_job_deadline",
    "find_repost_candidate",
    "reopen_job_for_repost",
    "AUTO_REOPEN_REASONS",
    "find_jobs_by_source_url_regex",
    "update_job_from_recrawl",
    "skip_updated_at_supported",
    "list_level_recompute_candidates",
    "compute_content_hashes_for_levels",
    "get_jobs_by_content_hashes",
    "count_duplicate_job_groups",
    "write_recomputed_levels",
    "list_duplicate_job_rows",
    "list_merge_job_details",
    "merge_job_group",
    "merge_job_enum_supported",
    "list_active_runs",
    "MergeStaleError",
    "MergeIntegrityError",
    "count_jobs",
    "find_manual_job_duplicate",
    "find_similar_open_jobs",
    "lock_job_dedup_key",
    "JobDedupLockTimeout",
    "JOB_DEDUP_LOCK_TIMEOUT_MS",
    "create_manual_job",
    "update_job",
    "JOB_UNSET",
    "JOB_CLOSED_REASONS",
    "JOB_CLEARABLE_FIELD_TO_COLUMN",
    "job_exists_by_id",
    "list_jobs",
    "get_job_by_id",
    "get_jobs_by_company_id",
    "get_job_data_health",
    "get_stats_summary",
    "get_job_engagement_counts",
    "get_monthly_engagement_stats",
    "get_jobs_needing_push",
    "get_stale_jobs",
    "get_top_skills",
    "get_salary_ranges",
    "get_high_potential_companies_without_contact",
    "get_contacts_needing_followup",
    "get_company_job_activity",
    "get_monthly_recap_counts",
    "get_user_by_email",
    "get_user_by_id",
    "create_user",
    "update_user_password",
    "update_user_profile",
    "record_failed_login",
    "is_account_locked",
    "reset_failed_login",
    "create_refresh_token",
    "get_refresh_token_by_hash",
    "get_refresh_token_by_id",
    "revoke_refresh_token",
    "set_active_session_id",
    "revoke_all_refresh_tokens_for_user",
    "list_users",
    "get_user_summary_by_id",
    "update_user_role",
    "update_user_active_status",
    "create_user_pending_verification",
    "get_user_by_verify_token_hash",
    "mark_email_verified",
    "set_new_verify_token",
    "set_password_reset_token",
    "get_user_by_reset_token_hash",
    "reset_password_with_token",
    "list_company_contacts",
    "list_all_contacts",
    "get_company_contact_by_id",
    "create_company_contact",
    "update_company_contact",
    "assign_company_contact",
    "soft_delete_company_contact",
    "ContactHasLinksError",
    "hard_delete_company_contact",
    "create_job_application",
    "list_applications_for_user",
    "list_applications_for_job",
    "delete_job_application",
    "create_saved_job",
    "list_saved_jobs_for_user",
    "delete_saved_job",
    "list_saved_jobs_for_job",
    "list_closed_job_applications_with_cv",
    "clear_application_cv",
    "get_application_cv_url",
    "set_application_cv_url",
    "get_application_with_job_info",
    "ACTION_LOG_RULES",
    "NoteRequiredError",
    "diff_changed_fields",
    "log_action",
    "list_audit_logs",
    "get_audit_log_by_id",
    "update_audit_log_note",
    "ActiveCrawlExistsError",
    "create_crawl_run",
    "mark_crawl_run_running",
    "mark_crawl_run_done",
    "mark_crawl_run_error",
    "get_crawl_run",
    "list_crawl_runs",
    "crawl_source_has_active_run",
    "reconcile_orphaned_crawl_runs",
    "reconcile_stale_crawl_runs",
    "update_crawl_run_progress",
    "append_crawl_run_log",
    "get_crawl_run_logs",
    "get_latest_crawl_run",
    "get_recent_blocked_crawl_run",
    "save_crawl_snapshots",
    "list_crawl_snapshots",
    "get_crawl_snapshot",
    "create_crawl_batch",
    "advance_crawl_batch",
    "mark_crawl_batch_done",
    "mark_crawl_batch_error",
    "get_crawl_batch",
    "get_crawl_batch_with_items",
    "list_crawl_batches",
    "ActiveMaintenanceRunExistsError",
    "create_maintenance_run",
    "mark_maintenance_run_running",
    "mark_maintenance_run_done",
    "mark_maintenance_run_error",
    "get_maintenance_run",
    "list_maintenance_runs",
    "maintenance_job_type_has_active_run",
    "reconcile_orphaned_maintenance_runs",
    "reconcile_stale_maintenance_runs",
    "append_maintenance_run_log",
    "get_maintenance_run_logs",
    "get_maintenance_run_logs_batch",
    "get_latest_maintenance_run_per_job_type",
    "MAX_PENDING_PER_STUDENT",
    "DECLINE_COOLDOWN_DAYS",
    "MAX_MESSAGE_ID",
    "get_relationship",
    "get_relationship_by_id",
    "count_pending_for_student",
    "create_pending_request",
    "cancel_pending_request",
    "reset_declined_to_pending",
    "accept_relationship",
    "decline_relationship",
    "block_relationship",
    "block_student_by_ss",
    "unblock_relationship",
    "ensure_accepted_by_ss",
    "insert_message",
    "get_message_by_id",
    "get_messages_between",
    "get_messages_since",
    "mark_read",
    "get_unread_count",
    "get_conversation_with",
    "list_conversations",
    "list_pending_requests_for_ss",
    "search_people",
]

